// Currency constants for destination mapping and currency info

export const DESTINATION_CURRENCIES: Record<string, string> = {
    // Europa
    'Portugal': 'EUR',
    'Espanha': 'EUR',
    'França': 'EUR',
    'Itália': 'EUR',
    'Alemanha': 'EUR',
    'Grécia': 'EUR',
    'Holanda': 'EUR',
    'Bélgica': 'EUR',
    'Áustria': 'EUR',
    'Irlanda': 'EUR',
    'Finlândia': 'EUR',
    'Reino Unido': 'GBP',
    'Inglaterra': 'GBP',
    'Escócia': 'GBP',
    'Suíça': 'CHF',
    'Noruega': 'NOK',
    'Suécia': 'SEK',
    'Dinamarca': 'DKK',
    'Polônia': 'PLN',
    'República Tcheca': 'CZK',
    'Hungria': 'HUF',
    'Croácia': 'EUR',
    'Turquia': 'TRY',
    'Rússia': 'RUB',

    // Américas
    'Estados Unidos': 'USD',
    'EUA': 'USD',
    'Canadá': 'CAD',
    'México': 'MXN',
    'Argentina': 'ARS',
    'Chile': 'CLP',
    'Colômbia': 'COP',
    'Peru': 'PEN',
    'Uruguai': 'UYU',
    'Paraguai': 'PYG',
    'Bolívia': 'BOB',
    'Equador': 'USD',
    'Costa Rica': 'CRC',
    'Panamá': 'USD',
    'Cuba': 'CUP',

    // Ásia
    'Japão': 'JPY',
    'China': 'CNY',
    'Tailândia': 'THB',
    'Coreia do Sul': 'KRW',
    'Índia': 'INR',
    'Indonésia': 'IDR',
    'Malásia': 'MYR',
    'Singapura': 'SGD',
    'Vietnã': 'VND',
    'Filipinas': 'PHP',
    'Taiwan': 'TWD',
    'Hong Kong': 'HKD',

    // Oceania
    'Austrália': 'AUD',
    'Nova Zelândia': 'NZD',

    // África
    'África do Sul': 'ZAR',
    'Egito': 'EGP',
    'Marrocos': 'MAD',
    'Quênia': 'KES',

    // Oriente Médio
    'Emirados Árabes': 'AED',
    'Dubai': 'AED',
    'Israel': 'ILS',
    'Arábia Saudita': 'SAR',
    'Qatar': 'QAR',
};

export const CURRENCY_INFO: Record<string, { symbol: string; name: string; flag: string }> = {
    'BRL': { symbol: 'R$', name: 'Real Brasileiro', flag: '🇧🇷' },
    'EUR': { symbol: '€', name: 'Euro', flag: '🇪🇺' },
    'USD': { symbol: '$', name: 'Dólar Americano', flag: '🇺🇸' },
    'GBP': { symbol: '£', name: 'Libra Esterlina', flag: '🇬🇧' },
    'JPY': { symbol: '¥', name: 'Iene Japonês', flag: '🇯🇵' },
    'CHF': { symbol: 'CHF', name: 'Franco Suíço', flag: '🇨🇭' },
    'CAD': { symbol: 'C$', name: 'Dólar Canadense', flag: '🇨🇦' },
    'AUD': { symbol: 'A$', name: 'Dólar Australiano', flag: '🇦🇺' },
    'NZD': { symbol: 'NZ$', name: 'Dólar Neozelandês', flag: '🇳🇿' },
    'CNY': { symbol: '¥', name: 'Yuan Chinês', flag: '🇨🇳' },
    'KRW': { symbol: '₩', name: 'Won Sul-Coreano', flag: '🇰🇷' },
    'INR': { symbol: '₹', name: 'Rupia Indiana', flag: '🇮🇳' },
    'MXN': { symbol: 'MX$', name: 'Peso Mexicano', flag: '🇲🇽' },
    'ARS': { symbol: 'AR$', name: 'Peso Argentino', flag: '🇦🇷' },
    'CLP': { symbol: 'CL$', name: 'Peso Chileno', flag: '🇨🇱' },
    'COP': { symbol: 'CO$', name: 'Peso Colombiano', flag: '🇨🇴' },
    'PEN': { symbol: 'S/', name: 'Sol Peruano', flag: '🇵🇪' },
    'UYU': { symbol: '$U', name: 'Peso Uruguaio', flag: '🇺🇾' },
    'THB': { symbol: '฿', name: 'Baht Tailandês', flag: '🇹🇭' },
    'SGD': { symbol: 'S$', name: 'Dólar de Singapura', flag: '🇸🇬' },
    'MYR': { symbol: 'RM', name: 'Ringgit Malaio', flag: '🇲🇾' },
    'IDR': { symbol: 'Rp', name: 'Rupia Indonésia', flag: '🇮🇩' },
    'PHP': { symbol: '₱', name: 'Peso Filipino', flag: '🇵🇭' },
    'VND': { symbol: '₫', name: 'Dong Vietnamita', flag: '🇻🇳' },
    'HKD': { symbol: 'HK$', name: 'Dólar de Hong Kong', flag: '🇭🇰' },
    'TWD': { symbol: 'NT$', name: 'Dólar Taiwanês', flag: '🇹🇼' },
    'ZAR': { symbol: 'R', name: 'Rand Sul-Africano', flag: '🇿🇦' },
    'AED': { symbol: 'د.إ', name: 'Dirham dos Emirados', flag: '🇦🇪' },
    'ILS': { symbol: '₪', name: 'Shekel Israelense', flag: '🇮🇱' },
    'TRY': { symbol: '₺', name: 'Lira Turca', flag: '🇹🇷' },
    'NOK': { symbol: 'kr', name: 'Coroa Norueguesa', flag: '🇳🇴' },
    'SEK': { symbol: 'kr', name: 'Coroa Sueca', flag: '🇸🇪' },
    'DKK': { symbol: 'kr', name: 'Coroa Dinamarquesa', flag: '🇩🇰' },
    'PLN': { symbol: 'zł', name: 'Zloty Polonês', flag: '🇵🇱' },
    'CZK': { symbol: 'Kč', name: 'Coroa Tcheca', flag: '🇨🇿' },
    'HUF': { symbol: 'Ft', name: 'Florim Húngaro', flag: '🇭🇺' },
    'RUB': { symbol: '₽', name: 'Rublo Russo', flag: '🇷🇺' },
    'EGP': { symbol: 'E£', name: 'Libra Egípcia', flag: '🇪🇬' },
    'MAD': { symbol: 'د.م.', name: 'Dirham Marroquino', flag: '🇲🇦' },
    'SAR': { symbol: '﷼', name: 'Riyal Saudita', flag: '🇸🇦' },
    'QAR': { symbol: '﷼', name: 'Riyal Qatari', flag: '🇶🇦' },
};

// Fallback static rates (approximate, used when API is unavailable)
export const FALLBACK_RATES: Record<string, number> = {
    'USD': 5.00,
    'EUR': 5.50,
    'GBP': 6.30,
    'JPY': 0.034,
    'CHF': 5.70,
    'CAD': 3.70,
    'AUD': 3.30,
    'NZD': 3.00,
    'CNY': 0.70,
    'KRW': 0.0038,
    'INR': 0.060,
    'MXN': 0.29,
    'ARS': 0.0058,
    'CLP': 0.0055,
    'COP': 0.0012,
    'PEN': 1.35,
    'UYU': 0.13,
    'THB': 0.14,
    'SGD': 3.75,
    'MYR': 1.10,
    'IDR': 0.00032,
    'PHP': 0.089,
    'VND': 0.00020,
    'HKD': 0.64,
    'TWD': 0.16,
    'ZAR': 0.27,
    'AED': 1.36,
    'ILS': 1.38,
    'TRY': 0.15,
    'NOK': 0.47,
    'SEK': 0.48,
    'DKK': 0.74,
    'PLN': 1.25,
    'CZK': 0.22,
    'HUF': 0.014,
    'RUB': 0.055,
    'EGP': 0.10,
    'MAD': 0.50,
    'SAR': 1.33,
    'QAR': 1.37,
};
