export const COUNTRIES_PT_BR = [
    "África do Sul", "Albânia", "Alemanha", "Andorra", "Angola", "Arábia Saudita", "Argélia", "Argentina", "Armênia", "Austrália", "Áustria", "Azerbaijão",
    "Bahamas", "Bangladesh", "Barbados", "Barein", "Bélgica", "Belize", "Benin", "Bielorrússia", "Bolívia", "Bósnia e Herzegovina", "Botsuana", "Brasil", "Brunei", "Bulgária", "Burkina Faso", "Burundi",
    "Butão", "Cabo Verde", "Camarões", "Camboja", "Canadá", "Catar", "Cazaquistão", "Chade", "Chile", "China", "Chipre", "Colômbia", "Comores", "Congo", "Coreia do Norte", "Coreia do Sul", "Costa do Marfim", "Costa Rica", "Croácia", "Cuba",
    "Dinamarca", "Djibuti", "Dominica", "Egito", "El Salvador", "Emirados Árabes Unidos", "Equador", "Eritreia", "Eslováquia", "Eslovênia", "Espanha", "Estados Unidos", "Estônia", "Etiópia",
    "Fiji", "Filipinas", "Finlândia", "França", "Gabão", "Gâmbia", "Gana", "Geórgia", "Granada", "Grécia", "Guatemala", "Guiana", "Guiné", "Guiné Equatorial", "Guiné-Bissau",
    "Haiti", "Holanda", "Honduras", "Hungria", "Iêmen", "Ilhas Marshall", "Ilhas Salomão", "Índia", "Indonésia", "Irã", "Iraque", "Irlanda", "Islândia", "Israel", "Itália",
    "Jamaica", "Japão", "Jordânia", "Kiribati", "Kuwait", "Laos", "Lesoto", "Letônia", "Líbano", "Libéria", "Líbia", "Liechtenstein", "Lituânia", "Luxemburgo",
    "Macedônia do Norte", "Madagascar", "Malásia", "Malawi", "Maldivas", "Mali", "Malta", "Marrocos", "Maurício", "Mauritânia", "México", "Micronésia", "Moçambique", "Moldávia", "Mônaco", "Mongólia", "Montenegro", "Myanmar",
    "Namíbia", "Nauru", "Nepal", "Nicarágua", "Níger", "Nigéria", "Noruega", "Nova Zelândia", "Omã", "Palau", "Panamá", "Papua Nova Guiné", "Paquistão", "Paraguai", "Peru", "Polônia", "Portugal",
    "Quênia", "Quirguistão", "Reino Unido", "República Centro-Africana", "República Checa", "República Democrática do Congo", "República Dominicana", "Romênia", "Ruanda", "Rússia",
    "Samoa", "Santa Lúcia", "São Cristóvão e Névis", "São Marino", "São Tomé e Príncipe", "São Vicente e Granadinas", "Senegal", "Serra Leoa", "Sérvia", "Seychelles", "Singapura", "Síria", "Somália", "Sri Lanka", "Suazilândia", "Sudão", "Sudão do Sul", "Suécia", "Suíça", "Suriname",
    "Tailândia", "Taiwan", "Tajiquistão", "Tanzânia", "Timor-Leste", "Togo", "Tonga", "Trinidad e Tobago", "Tunísia", "Turcomenistão", "Turquia", "Tuvalu",
    "Ucrânia", "Uganda", "Uruguai", "Uzbequistão", "Vanuatu", "Vaticano", "Venezuela", "Vietnã", "Zâmbia", "Zimbábue"
];

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
    "África do Sul": ["Cidade do Cabo", "Joanesburgo", "Durban", "Pretória"],
    "Alemanha": ["Berlim", "Munique", "Hamburgo", "Frankfurt", "Colônia", "Düsseldorf", "Dresden", "Nuremberg"],
    "Argentina": ["Buenos Aires", "Bariloche", "Mendoza", "Córdoba", "Ushuaia", "Rosário", "Salta"],
    "Austrália": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast"],
    "Áustria": ["Viena", "Salzburgo", "Innsbruck", "Graz", "Linz"],
    "Bélgica": ["Bruxelas", "Bruges", "Antuérpia", "Ghent"],
    "Brasil": ["Rio de Janeiro", "São Paulo", "Salvador", "Belo Horizonte", "Fortaleza", "Brasília", "Curitiba", "Recife", "Manaus", "Porto Alegre", "Florianópolis", "Gramado", "Foz do Iguaçu"],
    "Canadá": ["Toronto", "Vancouver", "Montreal", "Quebec", "Ottawa", "Calgary"],
    "Chile": ["Santiago", "Valparaíso", "San Pedro de Atacama", "Punta Arenas"],
    "China": ["Pequim", "Xangai", "Shenzhen", "Guangzhou", "Chengdu", "Xi'an", "Hong Kong", "Macau"],
    "Colômbia": ["Bogotá", "Cartagena", "Medellín", "Cali"],
    "Coreia do Sul": ["Seul", "Busan", "Incheon", "Jeju"],
    "Croácia": ["Dubrovnik", "Split", "Zagreb", "Hvar"],
    "Dinamarca": ["Copenhague", "Aarhus"],
    "Egito": ["Cairo", "Luxor", "Aswan", "Alexandria", "Hurghada"],
    "Emirados Árabes Unidos": ["Dubai", "Abu Dhabi", "Sharjah"],
    "Espanha": ["Madri", "Barcelona", "Sevilha", "Valência", "Granada", "Bilbao", "Ibiza", "Málaga", "Toledo"],
    "Estados Unidos": ["Nova York", "Los Angeles", "Orlando", "Miami", "Las Vegas", "São Francisco", "Chicago", "Boston", "Washington D.C.", "Honolulu", "San Diego", "Seattle", "Nova Orleans", "Austin"],
    "França": ["Paris", "Nice", "Marselha", "Lyon", "Bordeaux", "Estrasburgo", "Cannes", "Versalhes", "Chamonix"],
    "Grécia": ["Atenas", "Santorini", "Mykonos", "Creta", "Rodes", "Corfu"],
    "Holanda": ["Amsterdã", "Roterdã", "Haia", "Utrecht"],
    "Índia": ["Nova Délhi", "Mumbai", "Jaipur", "Agra", "Bangalore", "Goa"],
    "Irlanda": ["Dublin", "Cork", "Galway"],
    "Israel": ["Jerusalém", "Tel Aviv", "Haifa", "Eilat"],
    "Itália": ["Roma", "Veneza", "Florença", "Milão", "Nápoles", "Verona", "Turim", "Bolonha", "Pisa", "Siena", "Palermo", "Gênova"],
    "Japão": ["Tóquio", "Kyoto", "Osaka", "Hiroshima", "Sapporo", "Nara", "Yokohama"],
    "Marrocos": ["Marrakech", "Casablanca", "Fez", "Rabat", "Chefchaouen"],
    "México": ["Cidade do México", "Cancún", "Tulum", "Playa del Carmen", "Guadalajara", "Monterrey"],
    "Noruega": ["Oslo", "Bergen", "Tromsø"],
    "Peru": ["Lima", "Cusco", "Machu Picchu", "Arequipa"],
    "Portugal": ["Lisboa", "Porto", "Faro", "Sintra", "Coimbra", "Braga", "Funchal", "Cascais", "Évora"],
    "Reino Unido": ["Londres", "Edimburgo", "Manchester", "Liverpool", "Glasgow", "Oxford", "Cambridge", "Belfast"],
    "República Checa": ["Praga", "Brno", "Cesky Krumlov"],
    "Rússia": ["Moscou", "São Petersburgo"],
    "Singapura": ["Singapura"],
    "Suécia": ["Estocolmo", "Gotemburgo"],
    "Suíça": ["Zurique", "Genebra", "Lucerna", "Berna", "Interlaken", "Zermatt"],
    "Tailândia": ["Bangkok", "Phuket", "Chiang Mai", "Krabi", "Pattaya"],
    "Turquia": ["Istambul", "Capadócia", "Antalya", "Ankara", "Izmir"],
    "Uruguai": ["Montevidéu", "Punta del Este", "Colonia del Sacramento"]
};
