/**
 * LLM Analysis Types
 *
 * Types for the AI-powered contextual analysis layer that complements
 * the deterministic rule-based verification system.
 */

import { TaskCategory, TaskPriority, TaskUrgency, GeneratedTask } from '../types';

// =============================================================================
// Analysis Request/Response Types
// =============================================================================

/**
 * Trigger conditions for when to run LLM analysis
 */
export type AnalysisTrigger =
  | 'manual'              // User explicitly requested
  | 'new_trip'            // Trip just created
  | 'major_change'        // Significant trip modification
  | 'approaching_trip'    // Trip is within X days
  | 'periodic';           // Scheduled background check

/**
 * Confidence level of LLM suggestions
 */
export type ConfidenceLevel = 'high' | 'medium' | 'low';

/**
 * Source attribution for suggestions
 */
export type SuggestionSource = 'deterministic_rule' | 'llm_analysis' | 'hybrid';

/**
 * Categories of insights the LLM can provide
 */
export type InsightCategory =
  | 'timing'              // Time allocation issues
  | 'budget'              // Financial concerns
  | 'logistics'           // Travel logistics problems
  | 'local_events'        // Holidays, closures, events
  | 'weather'             // Weather-related alerts
  | 'health_safety'       // Health and safety concerns
  | 'cultural'            // Cultural considerations
  | 'optimization'        // Trip optimization suggestions
  | 'preparation';        // Pre-trip preparation

/**
 * An insight generated by LLM analysis
 */
export interface LLMInsight {
  id: string;
  category: InsightCategory;
  title: string;
  description: string;
  confidence: ConfidenceLevel;
  severity: 'critical' | 'warning' | 'info' | 'tip';

  // Affected parts of the trip
  affectedDestinations?: string[];
  affectedDates?: string[];
  affectedActivities?: string[];

  // Supporting evidence
  reasoning: string;
  sources?: string[];

  // Actionable information
  suggestedAction?: string;
  actionUrl?: string;
}

/**
 * A task suggested by LLM analysis
 * Extends GeneratedTask with LLM-specific metadata
 */
export interface LLMSuggestedTask extends Omit<GeneratedTask, 'ruleId' | 'ruleName'> {
  // LLM-specific metadata
  source: 'llm_analysis';
  confidence: ConfidenceLevel;
  reasoning: string;

  // Validation status
  validationStatus: 'pending' | 'validated' | 'rejected';
  validationNotes?: string;

  // User should verify
  requiresUserValidation: boolean;

  // LLM metadata
  llmModel: string;
  generatedAt: string;
  promptVersion: string;
}

/**
 * Complete result of an LLM analysis
 */
export interface LLMAnalysisResult {
  // Metadata
  tripId: string;
  analyzedAt: string;
  trigger: AnalysisTrigger;
  processingTimeMs: number;

  // Token usage (for cost tracking)
  tokenUsage: {
    inputTokens: number;
    outputTokens: number;
    cachedTokens?: number;
    estimatedCostUSD: number;
  };

  // Results
  insights: LLMInsight[];
  suggestedTasks: LLMSuggestedTask[];

  // Summary
  summary: {
    overallAssessment: 'excellent' | 'good' | 'needs_attention' | 'concerns';
    keyHighlights: string[];
    criticalIssues: number;
    warnings: number;
    tips: number;
  };

  // Raw response (for debugging)
  rawResponse?: string;
}

// =============================================================================
// Trip Serialization for LLM
// =============================================================================

/**
 * Serialized trip data optimized for LLM comprehension
 */
export interface SerializedTripForLLM {
  // Basic info
  tripId: string;
  title: string;
  totalDays: number;
  daysUntilDeparture: number;

  // Travelers
  travelers: {
    count: number;
    nationalities: string[];
    hasChildren: boolean;
    hasElderly: boolean;
    dietaryRestrictions?: string[];
    mobilityRestrictions?: string[];
  };

  // Destinations with context
  destinations: Array<{
    name: string;
    country: string;
    countryCode: string;
    arrivalDate: string;
    departureDate: string;
    nights: number;
    isSchengen?: boolean;
    altitude?: number;
    timezone?: string;
  }>;

  // Confirmed bookings
  bookings: {
    flights: Array<{
      from: string;
      to: string;
      date: string;
      time: string;
      airline: string;
      duration?: string;
    }>;
    hotels: Array<{
      name: string;
      city: string;
      checkIn: string;
      checkOut: string;
      nights: number;
    }>;
    activities: Array<{
      name: string;
      city: string;
      date: string;
      time?: string;
      duration?: string;
      isBooked: boolean;
    }>;
  };

  // Budget (if available)
  budget?: {
    total?: number;
    perDay?: number;
    currency: string;
  };

  // Existing preparation status
  existingTasks: Array<{
    text: string;
    completed: boolean;
    category: string;
  }>;

  // Notes and context
  userNotes?: string;
  tripType?: string;  // business, leisure, adventure, etc.
}

// =============================================================================
// Analysis Configuration
// =============================================================================

/**
 * Configuration for LLM analysis behavior
 */
export interface LLMAnalysisConfig {
  // Model settings
  model: string;
  temperature: number;
  maxTokens: number;

  // Cost control
  maxCostPerAnalysis: number;  // USD
  enableCaching: boolean;
  cacheExpirationHours: number;

  // Trigger thresholds
  autoTriggerDaysBeforeTrip: number;
  majorChangeThreshold: {
    destinationsChanged: boolean;
    datesChanged: boolean;
    durationChangedDays: number;
  };

  // Output control
  maxInsights: number;
  maxSuggestedTasks: number;
  confidenceThreshold: ConfidenceLevel;

  // Safety
  requireValidation: boolean;
  enableHallucinationDetection: boolean;
}

/**
 * Default analysis configuration
 */
export const DEFAULT_LLM_CONFIG: LLMAnalysisConfig = {
  model: 'gemini-2.5-flash',
  temperature: 0.3,  // Lower for more consistent outputs
  maxTokens: 4096,

  maxCostPerAnalysis: 0.05,  // $0.05 USD max per analysis
  enableCaching: true,
  cacheExpirationHours: 24,

  autoTriggerDaysBeforeTrip: 14,
  majorChangeThreshold: {
    destinationsChanged: true,
    datesChanged: true,
    durationChangedDays: 2,
  },

  maxInsights: 10,
  maxSuggestedTasks: 5,
  confidenceThreshold: 'medium',

  requireValidation: true,
  enableHallucinationDetection: true,
};

// =============================================================================
// Caching Types
// =============================================================================

/**
 * Cache entry for LLM analysis results
 */
export interface LLMAnalysisCacheEntry {
  tripId: string;
  tripHash: string;  // Hash of relevant trip data
  result: LLMAnalysisResult;
  cachedAt: number;
  expiresAt: number;
  promptVersion: string;
}

/**
 * Change detection for smart caching
 */
export interface TripChangeSignature {
  destinationHash: string;
  dateRange: string;
  travelerCount: number;
  bookingCount: number;
  taskCount: number;
}

// =============================================================================
// Prompt Caching Types (Gemini Context Caching)
// =============================================================================

/**
 * Structure for cached prompt context
 * These are parts of the prompt that don't change between trips
 */
export interface CachedPromptContext {
  // Travel knowledge base
  visaRequirements: string;
  healthRecommendations: string;
  commonTravelTips: string;

  // Analysis instructions
  outputFormat: string;
  qualityGuidelines: string;

  // Cached context ID from Gemini
  cachedContextId?: string;
  cachedAt?: number;
  expiresAt?: number;
}

// =============================================================================
// Validation Types
// =============================================================================

/**
 * Result of validating an LLM suggestion
 */
export interface ValidationResult {
  isValid: boolean;
  confidence: number;  // 0-1
  issues: ValidationIssue[];
}

/**
 * Types of validation issues
 */
export interface ValidationIssue {
  type: 'hallucination' | 'outdated' | 'implausible' | 'duplicate' | 'irrelevant';
  description: string;
  severity: 'blocking' | 'warning';
  field?: string;
}

/**
 * Hallucination detection patterns
 */
export interface HallucinationCheck {
  // Check if dates mentioned are within trip period
  datesInRange: boolean;
  // Check if destinations mentioned exist in trip
  destinationsValid: boolean;
  // Check if suggested costs are plausible
  costsPlausible: boolean;
  // Check if external links are valid
  urlsValid: boolean;
}
