import { PreparationTask } from '../types';

interface ChecklistRule {
    name: string;
    condition: (context: any) => boolean;
    task: PreparationTask;
}

export const checklistRules: ChecklistRule[] = [
    {
        name: 'NotifyBankRule',
        condition: () => true, // Always for now, assumig international context or just good practice
        task: {
            id: 'rule-notify-bank',
            title: 'Avisar banco sobre a viagem',
            description: 'Habilitar uso internacional nos cartões de crédito e débito.',
            category: 'financial',
            status: 'pending',
            isAutoGenerated: true,
            priority: 'high',
            deadline: undefined // Specific logic could set this relative to trip start
        }
    },
    {
        name: 'OfflineMapsRule',
        condition: () => true,
        task: {
            id: 'rule-offline-maps',
            title: 'Baixar mapas offline',
            description: 'Google Maps e aplicativos de transporte.',
            category: 'tech',
            status: 'pending',
            isAutoGenerated: true,
            priority: 'medium'
        }
    },
    {
        name: 'YellowFeverVaccineRule',
        condition: (context) => context?.requiresVaccine === true,
        task: {
            id: 'rule-yellow-fever',
            title: 'Vacina de Febre Amarela',
            description: 'Verificar se o certificado internacional está válido.',
            category: 'health',
            status: 'pending',
            isAutoGenerated: true,
            priority: 'high'
        }
    },
    {
        name: 'HighAltitudeMedicationRule',
        condition: (context) => context?.highAltitude === true,
        task: {
            id: 'rule-altitude-meds',
            title: 'Remédios para Altitude',
            description: 'Consultar médico sobre acetazolamida ou similares.',
            category: 'health',
            status: 'pending',
            isAutoGenerated: true,
            priority: 'medium'
        }
    }
];

export const generateAutoTasks = (startDate?: string, context: any = {}): PreparationTask[] => {
    return checklistRules
        .filter(rule => rule.condition(context))
        .map(rule => {
            let deadline: string | undefined = undefined;

            if (startDate) {
                const date = new Date(startDate);
                // Simple logic: most things 7 days before, simpler for MVP
                // In reality each rule could have a 'daysBeforeTrip' offset
                date.setDate(date.getDate() - 7);
                deadline = date.toISOString().split('T')[0];
            }

            return {
                ...rule.task,
                deadline,
                // Ensure unique instances if needed, though ID is static per rule currently
            };
        });
};
