// Country name (Portuguese) to ISO 2-letter code mapping
export const COUNTRY_CODES: Record<string, string> = {
    'japão': 'jp',
    'japao': 'jp',
    'frança': 'fr',
    'franca': 'fr',
    'grécia': 'gr',
    'grecia': 'gr',
    'brasil': 'br',
    'estados unidos': 'us',
    'eua': 'us',
    'portugal': 'pt',
    'espanha': 'es',
    'itália': 'it',
    'italia': 'it',
    'alemanha': 'de',
    'reino unido': 'gb',
    'inglaterra': 'gb',
    'argentina': 'ar',
    'chile': 'cl',
    'peru': 'pe',
    'colômbia': 'co',
    'colombia': 'co',
    'méxico': 'mx',
    'mexico': 'mx',
    'canadá': 'ca',
    'canada': 'ca',
    'austrália': 'au',
    'australia': 'au',
    'tailândia': 'th',
    'tailandia': 'th',
    'vietnã': 'vn',
    'vietnam': 'vn',
    'vietna': 'vn',
    'índia': 'in',
    'india': 'in',
    'china': 'cn',
    'coreia do sul': 'kr',
    'coreia': 'kr',
    'holanda': 'nl',
    'países baixos': 'nl',
    'suíça': 'ch',
    'suica': 'ch',
    'áustria': 'at',
    'austria': 'at',
    'bélgica': 'be',
    'belgica': 'be',
    'irlanda': 'ie',
    'noruega': 'no',
    'suécia': 'se',
    'suecia': 'se',
    'dinamarca': 'dk',
    'finlândia': 'fi',
    'finlandia': 'fi',
    'rússia': 'ru',
    'russia': 'ru',
    'turquia': 'tr',
    'egito': 'eg',
    'marrocos': 'ma',
    'áfrica do sul': 'za',
    'africa do sul': 'za',
    'nova zelândia': 'nz',
    'nova zelandia': 'nz',
    'indonésia': 'id',
    'indonesia': 'id',
    'malásia': 'my',
    'malasia': 'my',
    'singapura': 'sg',
    'filipinas': 'ph',
    'emirados árabes unidos': 'ae',
    'dubai': 'ae',
    'catar': 'qa',
    'israel': 'il',
    'polônia': 'pl',
    'polonia': 'pl',
    'república tcheca': 'cz',
    'tchéquia': 'cz',
    'hungria': 'hu',
    'croácia': 'hr',
    'croacia': 'hr',
    'cuba': 'cu',
    'uruguai': 'uy',
    'paraguai': 'py',
    'bolívia': 'bo',
    'bolivia': 'bo',
    'equador': 'ec',
    'panamá': 'pa',
    'panama': 'pa',
    'costa rica': 'cr',
    'porto rico': 'pr',
    'maldivas': 'mv',
    'ilhas maldivas': 'mv',
};

// Helper function to get flag URLs from destination string (comma separated)
export const getFlagsForDestinations = (destination: string): string[] => {
    if (!destination) return [];

    // Split by comma or ' e ' (case insensitive)
    const parts = destination.split(/,| e /i).map(d => d.trim().toLowerCase());

    const flags: string[] = [];
    parts.forEach(part => {
        if (COUNTRY_CODES[part]) {
            flags.push(`https://flagcdn.com/w40/${COUNTRY_CODES[part]}.png`);
        }
    });

    return flags;
};
