import React, { useState } from 'react';
import AIInputWizard from '../components/ai-assistant/v2/AIInputWizard';
import DestinationMetadataCardV2 from '../components/ai-assistant/v2/DestinationMetadataCardV2';
import ItineraryTimelineV2 from '../components/ai-assistant/v2/ItineraryTimelineV2';
import DestinationMapV2 from '../components/ai-assistant/v2/DestinationMapV2';
import { getGeminiService } from '../services/geminiService';
import {
    TravelPreferencesV2,
    AIGeneratedPlanV2,
    DestinationMetadata,
    AIItineraryDayV2,
    PreparationTask,
    ConnectivityAdvice,
    AppSuggestion,
} from '../types';

// Mock data for demonstration
const mockMetadata: DestinationMetadata = {
    name: 'Paris',
    country: 'França',
    timezone: 'CET (UTC+1)',
    currency: { code: 'EUR', symbol: '€', rateToBRL: 5.45 },
    language: 'Francês',
    voltage: '230V',
    plugType: 'C/E',
    visaRequired: false,
    visaNotes: 'Brasileiros não precisam de visto para estadias de até 90 dias',
    emergencyNumbers: { police: '17', ambulance: '15', fire: '18' },
};

const mockTasks: PreparationTask[] = [
    { id: '1', title: 'Verificar validade do passaporte', category: 'documentation', status: 'pending', isAutoGenerated: true, priority: 'high' },
    { id: '2', title: 'Comprar seguro viagem', category: 'documentation', status: 'pending', isAutoGenerated: true, priority: 'high' },
    { id: '3', title: 'Baixar mapa offline de Paris', category: 'tech', status: 'pending', isAutoGenerated: true, priority: 'medium' },
    { id: '4', title: 'Ativar eSIM internacional', category: 'tech', status: 'pending', isAutoGenerated: true, priority: 'medium' },
];

const mockApps: AppSuggestion[] = [
    { name: 'Citymapper', category: 'transport', reason: 'Melhor app de transporte público em Paris', isOfflineCapable: true },
    { name: 'Google Translate', category: 'translation', reason: 'Tradução offline de francês', isOfflineCapable: true },
    { name: 'Wise', category: 'payment', reason: 'Câmbio com melhores taxas', isOfflineCapable: false },
];

const mockConnectivity: ConnectivityAdvice = {
    recommendedType: 'esim',
    estimatedCost: 'R$ 80-120 (7 dias)',
    providers: ['Airalo', 'Holafly', 'Nomad'],
    notes: 'eSIM é a opção mais prática para a Europa',
};

const AIAssistantV2: React.FC = () => {
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [generatedPlan, setGeneratedPlan] = useState<AIGeneratedPlanV2 | null>(null);
    const [showResults, setShowResults] = useState(false);

    const handleSubmit = async (data: { destinations: string[]; preferences: TravelPreferencesV2 }) => {
        setLoading(true);
        setError(null);

        try {
            const geminiService = getGeminiService();

            // Convert preferences to API format
            const timing = {
                type: data.preferences.timing.type,
                startDate: data.preferences.timing.type === 'exact' ? (data.preferences.timing as any).startDate : undefined,
                endDate: data.preferences.timing.type === 'exact' ? (data.preferences.timing as any).endDate : undefined,
                month: data.preferences.timing.type === 'month' ? (data.preferences.timing as any).month : undefined,
                year: data.preferences.timing.type === 'month' ? (data.preferences.timing as any).year : undefined,
                duration: (data.preferences.timing as any).duration || 7,
                seasonPreference: data.preferences.timing.type === 'flexible' ? (data.preferences.timing as any).seasonPreference : undefined,
            };

            const party = {
                type: data.preferences.party.type,
                size: data.preferences.party.size,
                travelers: data.preferences.party.travelers.map(t => ({
                    ageGroup: t.ageGroup,
                    age: t.age,
                    dietaryRestrictions: t.dietaryRestrictions,
                    mobilityRestrictions: t.mobilityRestrictions,
                })),
            };

            const budget = {
                total: data.preferences.budget.total,
                accommodation: data.preferences.budget.accommodation,
                food: data.preferences.budget.food,
                transport: data.preferences.budget.transport,
                activities: data.preferences.budget.activities,
            };

            const plan = await geminiService.generateItineraryV2(
                data.destinations,
                timing,
                party,
                budget,
                data.preferences.interests
            );

            if (plan) {
                // Merge with input data to ensure all fields are present
                const fullPlan: AIGeneratedPlanV2 = {
                    ...plan,
                    timing: data.preferences.timing,
                    party: data.preferences.party,
                    budgetInput: data.preferences.budget,
                    interests: data.preferences.interests,
                };
                setGeneratedPlan(fullPlan);
                setShowResults(true);
            } else {
                throw new Error('Resposta vazia da IA');
            }
        } catch (err) {
            console.error('Error generating V2 itinerary:', err);
            setError('Não foi possível gerar o roteiro. Tente novamente.');
        } finally {
            setLoading(false);
        }
    };

    const handleBack = () => {
        setShowResults(false);
        setGeneratedPlan(null);
    };

    if (showResults && generatedPlan) {
        return (
            <div className="min-h-screen bg-[#EDEFF3] p-4 sm:p-8">
                <div className="max-w-6xl mx-auto">
                    {/* Header */}
                    <div className="flex items-center justify-between mb-8">
                        <div>
                            <button
                                onClick={handleBack}
                                className="flex items-center gap-2 text-[#9F9FB1] hover:text-[#1F1F1F] mb-2"
                            >
                                <span className="material-symbols-outlined">arrow_back</span>
                                Voltar
                            </button>
                            <h1 className="text-3xl font-bold text-[#1F1F1F]">
                                Sua Viagem para {generatedPlan.destinations.join(' + ')}
                            </h1>
                            <p className="text-[#9F9FB1] mt-1">
                                Roteiro personalizado gerado com IA
                            </p>
                        </div>
                        <button className="flex items-center gap-2 px-6 py-3 bg-[#6B68FF] text-white rounded-xl font-medium hover:bg-[#5a57e0] transition-colors">
                            <span className="material-symbols-outlined">bookmark</span>
                            Salvar Viagem
                        </button>
                    </div>

                    {/* Main Grid */}
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                        {/* Left Column - Metadata & Main Info */}
                        <div className="lg:col-span-2 space-y-6">
                            {/* Destination Metadata */}
                            {generatedPlan.destinationMetadata.map((meta, idx) => (
                                <DestinationMetadataCardV2 key={idx} metadata={meta} />
                            ))}

                            {/* Weather & Advisory */}
                            <div className="bg-white rounded-2xl p-6 border border-[#EDEFF3]">
                                <div className="flex items-start gap-4">
                                    <span className="material-symbols-outlined text-4xl text-[#6B68FF]">partly_cloudy_day</span>
                                    <div>
                                        <h3 className="font-bold text-[#1F1F1F]">Clima Esperado</h3>
                                        <p className="text-[#9F9FB1]">{generatedPlan.weatherSummary}</p>
                                        {generatedPlan.purchaseAdvice && (
                                            <div className="mt-3 p-3 bg-green-50 rounded-xl flex items-center gap-2">
                                                <span className="material-symbols-outlined text-green-600">tips_and_updates</span>
                                                <p className="text-sm text-green-700">{generatedPlan.purchaseAdvice}</p>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </div>

                            {/* Budget Summary */}
                            <div className="bg-white rounded-2xl p-6 border border-[#EDEFF3]">
                                <h3 className="font-bold text-[#1F1F1F] mb-4 flex items-center gap-2">
                                    <span className="material-symbols-outlined text-[#6B68FF]">account_balance_wallet</span>
                                    Resumo Financeiro
                                </h3>
                                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                                    <div className="text-center p-4 bg-[#EDEFF3] rounded-xl">
                                        <p className="text-xs text-[#9F9FB1] uppercase">Total</p>
                                        <p className="text-2xl font-bold text-[#6B68FF]">
                                            R$ {generatedPlan.totalEstimatedCost.toLocaleString('pt-BR')}
                                        </p>
                                    </div>
                                    <div className="text-center p-4 bg-[#EDEFF3] rounded-xl">
                                        <p className="text-xs text-[#9F9FB1] uppercase">Por Dia</p>
                                        <p className="text-2xl font-bold text-[#1F1F1F]">
                                            R$ {generatedPlan.costPerDay?.toLocaleString('pt-BR')}
                                        </p>
                                    </div>
                                    <div className="text-center p-4 bg-[#EDEFF3] rounded-xl">
                                        <p className="text-xs text-[#9F9FB1] uppercase">Hospedagem</p>
                                        <p className="text-2xl font-bold text-[#1F1F1F]">
                                            R$ {generatedPlan.estimatedBudget.accommodation?.toLocaleString('pt-BR')}
                                        </p>
                                    </div>
                                    <div className="text-center p-4 bg-[#EDEFF3] rounded-xl">
                                        <p className="text-xs text-[#9F9FB1] uppercase">Alimentação</p>
                                        <p className="text-2xl font-bold text-[#1F1F1F]">
                                            R$ {generatedPlan.estimatedBudget.food?.toLocaleString('pt-BR')}
                                        </p>
                                    </div>
                                </div>
                            </div>

                            {/* Destination Map */}
                            <DestinationMapV2
                                destinations={generatedPlan.destinations}
                                metadata={generatedPlan.destinationMetadata}
                            />

                            {/* Itinerary Timeline */}
                            {generatedPlan.days && generatedPlan.days.length > 0 ? (
                                <ItineraryTimelineV2 days={generatedPlan.days} />
                            ) : (
                                <div className="bg-white rounded-2xl p-6 border border-[#EDEFF3]">
                                    <h3 className="font-bold text-[#1F1F1F] mb-4 flex items-center gap-2">
                                        <span className="material-symbols-outlined text-[#6B68FF]">route</span>
                                        Roteiro Dia a Dia
                                    </h3>
                                    <div className="text-center py-8 text-[#9F9FB1]">
                                        <span className="material-symbols-outlined text-5xl mb-3 block">event_busy</span>
                                        <p>Nenhum dia detalhado foi gerado.</p>
                                        <p className="text-sm">A IA pode ter retornado dados parciais.</p>
                                    </div>
                                </div>
                            )}
                        </div>

                        {/* Right Column - Widgets */}
                        <div className="space-y-6">
                            {/* Preparation Checklist */}
                            <div className="bg-white rounded-2xl p-6 border border-[#EDEFF3]">
                                <h3 className="font-bold text-[#1F1F1F] mb-4 flex items-center gap-2">
                                    <span className="material-symbols-outlined text-[#6B68FF]">checklist</span>
                                    Preparação
                                </h3>
                                <div className="space-y-3">
                                    {generatedPlan.preparationTasks.map((task) => (
                                        <div key={task.id} className="flex items-center gap-3 p-3 bg-[#EDEFF3] rounded-xl">
                                            <button className={`w-6 h-6 rounded-full border-2 flex items-center justify-center ${task.status === 'done' ? 'bg-[#6B68FF] border-[#6B68FF]' : 'border-[#9F9FB1]'
                                                }`}>
                                                {task.status === 'done' && (
                                                    <span className="material-symbols-outlined text-white text-sm">check</span>
                                                )}
                                            </button>
                                            <div className="flex-1">
                                                <p className={`font-medium ${task.status === 'done' ? 'text-[#9F9FB1] line-through' : 'text-[#1F1F1F]'}`}>
                                                    {task.title}
                                                </p>
                                                <span className={`text-xs px-2 py-0.5 rounded ${task.priority === 'high' ? 'bg-red-100 text-red-600' :
                                                    task.priority === 'medium' ? 'bg-yellow-100 text-yellow-600' :
                                                        'bg-gray-100 text-gray-600'
                                                    }`}>
                                                    {task.priority === 'high' ? 'Alta' : task.priority === 'medium' ? 'Média' : 'Baixa'}
                                                </span>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {/* Connectivity */}
                            {generatedPlan.connectivityAdvice && (
                                <div className="bg-white rounded-2xl p-6 border border-[#EDEFF3]">
                                    <h3 className="font-bold text-[#1F1F1F] mb-4 flex items-center gap-2">
                                        <span className="material-symbols-outlined text-[#6B68FF]">wifi</span>
                                        Conectividade
                                    </h3>
                                    <div className="space-y-3">
                                        <div className="flex items-center justify-between p-3 bg-[#6B68FF]/10 rounded-xl">
                                            <span className="font-medium text-[#6B68FF]">Recomendado</span>
                                            <span className="font-bold text-[#6B68FF] uppercase">
                                                {generatedPlan.connectivityAdvice.recommendedType}
                                            </span>
                                        </div>
                                        <p className="text-sm text-[#9F9FB1]">
                                            Custo estimado: {generatedPlan.connectivityAdvice.estimatedCost}
                                        </p>
                                        {generatedPlan.connectivityAdvice.providers && (
                                            <div className="flex flex-wrap gap-2">
                                                {generatedPlan.connectivityAdvice.providers.map((p, idx) => (
                                                    <span key={idx} className="px-3 py-1 bg-[#EDEFF3] rounded-lg text-sm text-[#1F1F1F]">
                                                        {p}
                                                    </span>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                </div>
                            )}

                            {/* Suggested Apps */}
                            {generatedPlan.suggestedApps && generatedPlan.suggestedApps.length > 0 && (
                                <div className="bg-white rounded-2xl p-6 border border-[#EDEFF3]">
                                    <h3 className="font-bold text-[#1F1F1F] mb-4 flex items-center gap-2">
                                        <span className="material-symbols-outlined text-[#6B68FF]">apps</span>
                                        Apps Recomendados
                                    </h3>
                                    <div className="space-y-3">
                                        {generatedPlan.suggestedApps.map((app, idx) => (
                                            <div key={idx} className="flex items-center gap-3 p-3 bg-[#EDEFF3] rounded-xl">
                                                <div className="w-10 h-10 bg-[#6B68FF]/20 rounded-xl flex items-center justify-center">
                                                    <span className="material-symbols-outlined text-[#6B68FF]">
                                                        {app.category === 'transport' ? 'directions_bus' :
                                                            app.category === 'maps' ? 'map' :
                                                                app.category === 'translation' ? 'translate' :
                                                                    app.category === 'payment' ? 'payments' : 'apps'}
                                                    </span>
                                                </div>
                                                <div className="flex-1">
                                                    <p className="font-medium text-[#1F1F1F]">{app.name}</p>
                                                    <p className="text-xs text-[#9F9FB1]">{app.reason}</p>
                                                </div>
                                                {app.isOfflineCapable && (
                                                    <span className="material-symbols-outlined text-green-500" title="Funciona offline">
                                                        cloud_off
                                                    </span>
                                                )}
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-[#EDEFF3] p-4 sm:p-8">
            <div className="max-w-4xl mx-auto">
                {/* Header */}
                <div className="text-center mb-8">
                    <h1 className="text-4xl font-bold text-[#1F1F1F] mb-2">
                        Planeje sua Viagem com IA ✨
                    </h1>
                    <p className="text-[#9F9FB1] text-lg">
                        Responda algumas perguntas e deixe a mágica acontecer
                    </p>
                </div>

                {/* Wizard */}
                <AIInputWizard onSubmit={handleSubmit} loading={loading} />

                {/* V2 Badge */}
                <div className="text-center mt-6">
                    <span className="inline-flex items-center gap-2 px-4 py-2 bg-[#6B68FF]/10 text-[#6B68FF] rounded-full text-sm font-medium">
                        <span className="material-symbols-outlined text-lg">science</span>
                        Versão Beta V2
                    </span>
                </div>
            </div>
        </div>
    );
};

export default AIAssistantV2;
