import React, { useState, useEffect, useMemo } from 'react';
import { PreparationTask, Trip, TripContext, ChecklistTask } from '../../../types';
import { ChecklistTimeline } from '../../trip-details/checklist/ChecklistTimeline';
import { ChecklistSummary } from '../../trip-details/checklist/ChecklistSummary';
import { checklistNotificationService } from '../../../services/checklistNotificationService';
import { useTaskPriority } from '../../../hooks/useTaskPriority';
import { useLocalStorage } from '../../../hooks/useLocalStorage';
import { checklistRules, generateAutoTasks } from '../../../services/checklistRules';
import { useLLMAnalysis } from '../../../hooks/useLLMAnalysis';
import { AIInsights } from './AIInsights';

interface TaskChecklistProps {
    cityName?: string;
    tripId?: string;
    trip?: Trip; // Full trip context for IA
    startDate?: string;
}

export const TaskChecklist: React.FC<TaskChecklistProps> = ({ cityName, tripId = 'current-trip', trip, startDate }) => {
    // Persist tasks in local storage
    const [tasks, setTasks] = useLocalStorage<PreparationTask[]>(`checklist-${tripId}`, []);

    const {
        isAnalyzing,
        analysisResult,
        analyzeChecklist,
        acceptSuggestion: acceptAISuggestion,
        rejectSuggestion: rejectAISuggestion,
        clearAnalysis
    } = useLLMAnalysis(tripId);

    const tripContext = useMemo((): TripContext | null => {
        if (!trip) return null;
        return {
            destination: trip.destination,
            startDate: trip.startDate,
            endDate: trip.endDate,
            travelers: trip.participants,
            interests: [] // Can be expanded
        };
    }, [trip]);

    const handleAIAnalysis = async () => {
        if (tripContext) {
            await analyzeChecklist(tripContext);
        }
    };

    const handleAcceptAISuggestion = (suggestion: ChecklistTask) => {
        const newTask: PreparationTask = {
            id: `task-ai-${Date.now()}`,
            title: suggestion.title,
            deadline: undefined, // AI could suggest deadlines in future
            status: 'pending',
            category: (suggestion.category === 'documents' ? 'documentation' : suggestion.category) as any,
            isAutoGenerated: true,
            priority: suggestion.isUrgent ? 'high' : 'medium'
        };

        setTasks(prev => [...prev, newTask]);
        acceptAISuggestion(suggestion.id);
    };

    // Auto-populate if empty on first load
    useEffect(() => {
        if (tasks.length === 0) {
            const initialTasks = generateAutoTasks(startDate);
            setTasks(initialTasks);
        }
    }, [startDate]); // Run if startDate changes/populates


    // UI Local State
    const [newTaskTitle, setNewTaskTitle] = useState('');
    const [isAddingTask, setIsAddingTask] = useState(false);
    const [newTaskDeadline, setNewTaskDeadline] = useState('');
    const [newTaskPriority, setNewTaskPriority] = useState<'low' | 'medium' | 'high'>('medium');

    const { getDaysRemaining } = useTaskPriority();

    // Stats Logic
    const stats = useMemo(() => {
        return {
            total: tasks.length,
            completed: tasks.filter(t => t.status === 'done').length,
            overdue: tasks.filter(t => {
                if (t.status === 'done' || !t.deadline) return false;
                const days = getDaysRemaining(t.deadline);
                return days !== null && days < 0;
            }).length,
            upcoming: tasks.filter(t => {
                if (t.status === 'done' || !t.deadline) return false;
                const days = getDaysRemaining(t.deadline);
                return days !== null && days >= 0 && days <= 3;
            }).length
        };
    }, [tasks, getDaysRemaining]);

    // Check for notifications
    useEffect(() => {
        const userId = 'current-user';
        checklistNotificationService.checkAndNotify(tasks, userId, tripId);
    }, [tasks, tripId]);

    const handleToggleTask = (taskId: string) => {
        setTasks(prev => prev.map(t => {
            if (t.id === taskId) {
                return { ...t, status: t.status === 'done' ? 'pending' : 'done' };
            }
            return t;
        }));
    };

    const handleDeleteTask = (taskId: string) => {
        setTasks(prev => prev.filter(t => t.id !== taskId));
    };

    const handleAddTask = () => {
        if (!newTaskTitle.trim()) return;

        const newTask: PreparationTask = {
            id: `task-${Date.now()}`,
            title: newTaskTitle,
            deadline: newTaskDeadline || undefined,
            status: 'pending',
            category: 'packing', // Default
            isAutoGenerated: false,
            priority: newTaskPriority
        };

        setTasks(prev => [...prev, newTask]);

        // Reset form
        setNewTaskTitle('');
        setNewTaskDeadline('');
        setNewTaskPriority('medium');
        setIsAddingTask(false);
    };

    return (
        <div className="space-y-6">
            <ChecklistSummary
                totalTasks={stats.total}
                completedTasks={stats.completed}
                overdueTasks={stats.overdue}
                upcomingTasks={stats.upcoming}
            />

            {/* AI Analysis Section */}
            {analysisResult && (
                <AIInsights
                    insights={analysisResult.insights}
                    suggestions={analysisResult.suggestedTasks}
                    onAccept={handleAcceptAISuggestion}
                    onReject={rejectAISuggestion}
                    onDismissInsight={() => { }}
                />
            )}

            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden p-4">
                <div className="flex items-center justify-between mb-4">
                    <div className="flex items-center gap-3">
                        <h3 className="font-bold text-gray-800">Sua Timeline</h3>
                        <button
                            onClick={handleAIAnalysis}
                            disabled={isAnalyzing || !trip}
                            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all shadow-sm ${isAnalyzing
                                ? 'bg-indigo-50 text-indigo-400 cursor-wait'
                                : 'bg-indigo-600 text-white hover:bg-indigo-700 active:scale-95 shadow-indigo-100'
                                }`}
                        >
                            {isAnalyzing ? (
                                <>
                                    <div className="size-3 border-2 border-indigo-200 border-t-indigo-500 rounded-full animate-spin" />
                                    Analisando...
                                </>
                            ) : (
                                <>
                                    <span className="material-symbols-outlined text-sm">auto_awesome</span>
                                    Analisar com IA
                                </>
                            )}
                        </button>
                    </div>
                    <button
                        onClick={() => setIsAddingTask(!isAddingTask)}
                        className="text-sm font-semibold text-amber-600 hover:text-amber-700 flex items-center gap-1"
                    >
                        <span className="material-symbols-outlined">add_circle</span>
                        Nova Tarefa
                    </button>
                </div>

                {isAddingTask && (
                    <div className="mb-6 bg-gray-50 p-4 rounded-xl border border-gray-100 animate-in fade-in slide-in-from-top-2">
                        <input
                            type="text"
                            value={newTaskTitle}
                            onChange={(e) => setNewTaskTitle(e.target.value)}
                            placeholder="O que você precisa fazer?"
                            className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg outline-none focus:border-amber-500 mb-3"
                            autoFocus
                        />
                        <div className="flex gap-2">
                            <input
                                type="date"
                                value={newTaskDeadline}
                                onChange={(e) => setNewTaskDeadline(e.target.value)}
                                className="px-3 py-2 text-sm border border-gray-200 rounded-lg outline-none focus:border-amber-500 text-gray-600"
                            />
                            <select
                                value={newTaskPriority}
                                onChange={(e) => setNewTaskPriority(e.target.value as any)}
                                className="px-3 py-2 text-sm border border-gray-200 rounded-lg outline-none focus:border-amber-500 bg-white text-gray-600"
                            >
                                <option value="low">Baixa Prioridade</option>
                                <option value="medium">Média</option>
                                <option value="high">Alta Urgência</option>
                            </select>
                            <button
                                onClick={handleAddTask}
                                className="ml-auto px-4 py-2 bg-amber-500 text-white font-bold text-sm rounded-lg hover:bg-amber-600 transition-colors"
                            >
                                Adicionar
                            </button>
                        </div>
                    </div>
                )}

                <ChecklistTimeline
                    tasks={tasks}
                    onToggle={handleToggleTask}
                    onDelete={handleDeleteTask}
                />
            </div>
        </div>
    );
};

export default TaskChecklist;
