import React, { useState, useEffect, useMemo } from 'react';
import { PreparationTask, Trip, TripContext, ChecklistTask } from '../../../types';
import { checklistNotificationService } from '../../../services/checklistNotificationService';
import { useTaskPriority } from '../../../hooks/useTaskPriority';
import { useLocalStorage } from '../../../hooks/useLocalStorage';
import { generateAutoTasks } from '../../../services/checklistRules';
import { useLLMAnalysis } from '../../../hooks/useLLMAnalysis';
import { AIInsights } from './AIInsights';
import { EmptyState } from '../../ui/EmptyState';

// Category metadata (igual ao SmartChecklist)
type TaskCategory = 'documentation' | 'health' | 'reservations' | 'packing' | 'financial' | 'tech' | 'other';

const CATEGORY_CONFIG: Record<TaskCategory, { icon: string; label: string; color: string }> = {
    documentation: { icon: 'description', label: 'Documentação', color: 'blue' },
    health: { icon: 'health_and_safety', label: 'Saúde', color: 'green' },
    reservations: { icon: 'book_online', label: 'Reservas', color: 'purple' },
    packing: { icon: 'luggage', label: 'Bagagem', color: 'orange' },
    financial: { icon: 'payments', label: 'Financeiro', color: 'emerald' },
    tech: { icon: 'devices', label: 'Tecnologia', color: 'cyan' },
    other: { icon: 'task_alt', label: 'Outros', color: 'gray' }
};

// Priority badge colors
const PRIORITY_COLORS = {
    high: 'bg-red-100 text-red-700 border-red-200',
    medium: 'bg-amber-100 text-amber-700 border-amber-200',
    low: 'bg-blue-100 text-blue-700 border-blue-200'
};

const PRIORITY_LABELS = {
    high: 'Crítico',
    medium: 'Importante',
    low: 'Recomendado'
};

interface TaskChecklistProps {
    cityName?: string;
    tripId?: string;
    trip?: Trip; // Full trip context for IA
    startDate?: string;
}

export const TaskChecklist: React.FC<TaskChecklistProps> = ({ cityName, tripId = 'current-trip', trip, startDate }) => {
    // Persist tasks in local storage
    const [tasks, setTasks] = useLocalStorage<PreparationTask[]>(`checklist-${tripId}`, []);

    const {
        isAnalyzing,
        analysisResult,
        analyzeChecklist,
        acceptSuggestion: acceptAISuggestion,
        rejectSuggestion: rejectAISuggestion,
        clearAnalysis
    } = useLLMAnalysis(tripId);

    const tripContext = useMemo((): TripContext | null => {
        if (!trip) return null;
        return {
            destination: trip.destination,
            startDate: trip.startDate,
            endDate: trip.endDate,
            travelers: trip.participants,
            interests: [] // Can be expanded
        };
    }, [trip]);

    // Loading state messages for better UX
    const [loadingMessage, setLoadingMessage] = useState('');

    const handleAIAnalysis = async () => {
        if (tripContext) {
            // Progressive loading messages
            const messages = [
                'Analisando destino...',
                'Verificando clima...',
                'Gerando sugestões...',
                'Finalizando...'
            ];
            let messageIndex = 0;
            setLoadingMessage(messages[0]);

            const interval = setInterval(() => {
                messageIndex = (messageIndex + 1) % messages.length;
                setLoadingMessage(messages[messageIndex]);
            }, 1500);

            // Pass existing task titles to filter duplicates
            const existingTaskTitles = tasks.map(t => t.title);
            await analyzeChecklist(tripContext, existingTaskTitles);

            clearInterval(interval);
            setLoadingMessage('');
        }
    };

    const handleAcceptAISuggestion = (suggestion: ChecklistTask) => {
        const newTask: PreparationTask = {
            id: `task-ai-${Date.now()}`,
            title: suggestion.title,
            deadline: undefined, // AI could suggest deadlines in future
            status: 'pending',
            category: (suggestion.category === 'documents' ? 'documentation' : suggestion.category) as any,
            isAutoGenerated: true,
            priority: suggestion.isUrgent ? 'high' : 'medium'
        };

        setTasks(prev => [...prev, newTask]);
        acceptAISuggestion(suggestion.id);
    };

    // Auto-populate if empty on first load
    useEffect(() => {
        if (tasks.length === 0) {
            const initialTasks = generateAutoTasks(startDate);
            setTasks(initialTasks);
        }
    }, [startDate]); // Run if startDate changes/populates


    // UI Local State
    const [newTaskTitle, setNewTaskTitle] = useState('');
    const [isAddingTask, setIsAddingTask] = useState(false);
    // Removed complex state for manual add to match SmartChecklist functionality
    // const [newTaskDeadline, setNewTaskDeadline] = useState('');
    // const [newTaskPriority, setNewTaskPriority] = useState<'low' | 'medium' | 'high'>('medium');

    const { getDaysRemaining } = useTaskPriority();
    const [expandedCategories, setExpandedCategories] = useState<Set<TaskCategory>>(new Set(['packing', 'documentation']));
    const [showAnalysis, setShowAnalysis] = useState(false); // Add state to control AI visibility if needed, similar to SmartChecklist

    // Group tasks by category (igual ao SmartChecklist)
    const tasksByCategory = useMemo(() => {
        const grouped: Partial<Record<TaskCategory, PreparationTask[]>> = {};
        tasks.forEach(task => {
            const category = (task.category || 'other') as TaskCategory;
            if (!grouped[category]) {
                grouped[category] = [];
            }
            grouped[category]!.push(task);
        });
        return grouped;
    }, [tasks]);

    // Stats Logic
    const stats = useMemo(() => {
        const critical = tasks.filter(t => t.priority === 'high' && t.status !== 'done').length;
        return {
            total: tasks.length,
            completed: tasks.filter(t => t.status === 'done').length,
            critical,
            overdue: tasks.filter(t => {
                if (t.status === 'done' || !t.deadline) return false;
                const days = getDaysRemaining(t.deadline);
                return days !== null && days < 0;
            }).length,
            upcoming: tasks.filter(t => {
                if (t.status === 'done' || !t.deadline) return false;
                const days = getDaysRemaining(t.deadline);
                return days !== null && days >= 0 && days <= 3;
            }).length
        };
    }, [tasks, getDaysRemaining]);

    const toggleCategory = (category: TaskCategory) => {
        setExpandedCategories(prev => {
            const newSet = new Set(prev);
            if (newSet.has(category)) {
                newSet.delete(category);
            } else {
                newSet.add(category);
            }
            return newSet;
        });
    };

    const formatDueDate = (deadline?: string) => {
        if (!deadline) return null;

        const days = getDaysRemaining(deadline);
        if (days === null) return null;

        if (days < 0) {
            return { text: `Atrasado ${Math.abs(days)}d`, color: 'text-red-600' };
        } else if (days === 0) {
            return { text: 'Hoje', color: 'text-orange-600' };
        } else if (days <= 7) {
            return { text: `Em ${days}d`, color: 'text-amber-600' };
        } else {
            return { text: new Date(deadline).toLocaleDateString('pt-BR'), color: 'text-gray-600' };
        }
    };

    // Check for notifications
    useEffect(() => {
        const userId = 'current-user';
        checklistNotificationService.checkAndNotify(tasks, userId, tripId);
    }, [tasks, tripId]);

    const handleToggleTask = (taskId: string) => {
        setTasks(prev => prev.map(t => {
            if (t.id === taskId) {
                return { ...t, status: t.status === 'done' ? 'pending' : 'done' };
            }
            return t;
        }));
    };

    const handleDeleteTask = (taskId: string) => {
        setTasks(prev => prev.filter(t => t.id !== taskId));
    };

    const handleAddTask = () => {
        if (!newTaskTitle.trim()) return;

        const newTask: PreparationTask = {
            id: `task-${Date.now()}`,
            title: newTaskTitle,
            deadline: undefined, // Default to no deadline for quick add
            status: 'pending',
            category: 'packing', // Default
            isAutoGenerated: false,
            priority: 'medium' // Default
        };

        setTasks(prev => [...prev, newTask]);

        // Reset form
        setNewTaskTitle('');
        setIsAddingTask(false);
    };

    // Wrapper to handle AI interaction setting showAnalysis
    const handleRunAnalysis = async () => {
        setShowAnalysis(true);
        await handleAIAnalysis();
    };

    const handleDismissInsight = (_id: string) => {
        // Implementation for dismissing insights if needed
    };

    const handleAcceptAll = () => {
        if (!analysisResult) return;
        analysisResult.suggestedTasks.forEach(handleAcceptAISuggestion);
        clearAnalysis();
    };


    return (
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
            {/* Header with Summary */}
            <div className="px-6 py-4 border-b border-gray-100">
                <div className="flex items-center justify-between mb-3">
                    <h3 className="text-base font-bold text-text-main">Checklist de Bagagem</h3>
                    <div className="flex items-center gap-2">
                        <button
                            onClick={handleRunAnalysis}
                            disabled={isAnalyzing || !trip}
                            className={`px-3 py-1.5 text-xs font-bold rounded-lg shadow-sm transition-all flex items-center gap-1.5 ${isAnalyzing
                                ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                                : 'bg-gradient-to-r from-indigo-500 to-purple-500 text-white hover:from-indigo-600 hover:to-purple-600'
                                }`}
                        >
                            <span className={`material-symbols-outlined text-base ${isAnalyzing ? 'animate-spin' : ''}`}>
                                {isAnalyzing ? 'progress_activity' : 'auto_awesome'}
                            </span>
                            {isAnalyzing ? (loadingMessage || 'Analisando...') : 'Analisar com IA'}
                        </button>
                        <span className="text-xs font-medium text-text-muted">
                            {stats.completed}/{stats.total} concluídas
                        </span>
                    </div>
                </div>

                {/* Progress Bar */}
                <div className="w-full bg-gray-100 rounded-full h-2 overflow-hidden">
                    <div
                        className="h-full bg-gradient-to-r from-sky-500 to-emerald-500 transition-all duration-500"
                        style={{ width: `${stats.total > 0 ? (stats.completed / stats.total) * 100 : 0}%` }}
                    />
                </div>

                {/* Alerts */}
                {stats.critical > 0 && (
                    <div className="mt-3 flex items-center gap-2 text-xs text-red-600 bg-red-50 px-3 py-2 rounded-lg">
                        <span className="material-symbols-outlined text-sm">warning</span>
                        <span className="font-medium">{stats.critical} tarefa(s) crítica(s) pendente(s)</span>
                    </div>
                )}
                {stats.overdue > 0 && (
                    <div className="mt-2 flex items-center gap-2 text-xs text-orange-600 bg-orange-50 px-3 py-2 rounded-lg">
                        <span className="material-symbols-outlined text-sm">schedule</span>
                        <span className="font-medium">{stats.overdue} tarefa(s) atrasada(s)</span>
                    </div>
                )}
            </div>

            {/* AI Insights Section */}
            {(showAnalysis || analysisResult) && (
                <div className="px-6 py-4 border-b border-gray-100 bg-gradient-to-br from-indigo-50/30 to-purple-50/20">
                    {isAnalyzing ? (
                        <div className="flex items-center justify-center gap-3 py-6">
                            <span className="material-symbols-outlined text-2xl text-indigo-500 animate-spin">progress_activity</span>
                            <div>
                                <p className="text-sm font-medium text-indigo-700">Analisando bagagem...</p>
                                <p className="text-xs text-indigo-500">Gerando sugestões personalizadas para seu destino</p>
                            </div>
                        </div>
                    ) : analysisResult && (analysisResult.insights.length > 0 || analysisResult.suggestedTasks.length > 0) ? (
                        <AIInsights
                            insights={analysisResult.insights}
                            suggestions={analysisResult.suggestedTasks}
                            onAccept={handleAcceptAISuggestion}
                            onReject={rejectAISuggestion}
                            onDismissInsight={handleDismissInsight}
                            onAcceptAll={handleAcceptAll}
                        />
                    ) : showAnalysis && (
                        <div className="text-center py-4">
                            <span className="material-symbols-outlined text-3xl text-gray-400 mb-2">check_circle</span>
                            <p className="text-sm text-gray-600">Sua mala já está bem preparada!</p>
                            <p className="text-xs text-gray-400">Nenhuma sugestão adicional no momento.</p>
                        </div>
                    )}
                </div>
            )}

            {/* Task List by Category */}
            <div className="divide-y divide-gray-50">
                {tasks.length === 0 ? (
                    <div className="py-8">
                        <EmptyState
                            variant="minimal"
                            icon="checklist"
                            title="Nenhuma tarefa"
                            description="Adicione tarefas para começar a planejar sua mala."
                        />
                    </div>
                ) : (
                    Object.entries(tasksByCategory).map(([category, categoryTasks]) => {
                        const config = CATEGORY_CONFIG[category as TaskCategory];
                        const isExpanded = expandedCategories.has(category as TaskCategory);
                        const completedCount = categoryTasks?.filter(t => t.status === 'done').length || 0;
                        const totalCount = categoryTasks?.length || 0;

                        return (
                            <div key={category}>
                                {/* Category Header */}
                                <button
                                    onClick={() => toggleCategory(category as TaskCategory)}
                                    className="w-full px-6 py-3 flex items-center justify-between hover:bg-gray-50/50 transition-colors"
                                >
                                    <div className="flex items-center gap-3">
                                        <div className={`size-8 rounded-lg bg-${config.color}-50 text-${config.color}-600 flex items-center justify-center`}>
                                            <span className="material-symbols-outlined text-lg">{config.icon}</span>
                                        </div>
                                        <span className="font-semibold text-sm text-gray-800">{config.label}</span>
                                        <span className="text-xs text-gray-500">
                                            {completedCount}/{totalCount}
                                        </span>
                                    </div>
                                    <span className={`material-symbols-outlined text-gray-400 transition-transform ${isExpanded ? 'rotate-180' : ''}`}>
                                        expand_more
                                    </span>
                                </button>

                                {/* Category Tasks */}
                                {isExpanded && (
                                    <div className="bg-gray-50/30">
                                        {categoryTasks?.map(task => {
                                            const dueDateInfo = formatDueDate(task.deadline);

                                            return (
                                                <div
                                                    key={task.id}
                                                    className={`px-6 py-4 flex items-center gap-4 hover:bg-white/50 transition-colors border-l-2 ${task.priority === 'high' ? 'border-red-400' :
                                                        task.priority === 'medium' ? 'border-amber-400' :
                                                            'border-transparent'
                                                        } ${task.status === 'done' ? 'opacity-60' : ''}`}
                                                >
                                                    {/* Checkbox */}
                                                    <button
                                                        onClick={() => handleToggleTask(task.id)}
                                                        className={`size-6 rounded-full border-2 flex items-center justify-center transition-all shrink-0 ${task.status === 'done'
                                                            ? 'bg-green-500 border-green-500 text-white'
                                                            : 'border-gray-300 hover:border-gray-400'
                                                            }`}
                                                    >
                                                        {task.status === 'done' && (
                                                            <span className="material-symbols-outlined text-sm">check</span>
                                                        )}
                                                    </button>

                                                    {/* Content */}
                                                    <div className="flex-1 min-w-0">
                                                        <p className={`font-semibold text-sm ${task.status === 'done' ? 'line-through text-text-muted' : 'text-text-main'
                                                            }`}>
                                                            {task.title}
                                                        </p>
                                                        <div className="flex items-center gap-2 mt-1">
                                                            {task.priority && (
                                                                <span className={`px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider rounded border ${PRIORITY_COLORS[task.priority]}`}>
                                                                    {PRIORITY_LABELS[task.priority]}
                                                                </span>
                                                            )}
                                                            {dueDateInfo && (
                                                                <span className={`text-xs flex items-center gap-1 ${dueDateInfo.color}`}>
                                                                    <span className="material-symbols-outlined text-sm">event</span>
                                                                    {dueDateInfo.text}
                                                                </span>
                                                            )}
                                                            {task.isAutoGenerated && (
                                                                <span className="text-[10px] text-gray-400 flex items-center gap-1">
                                                                    <span className="material-symbols-outlined text-xs">auto_awesome</span>
                                                                    Auto
                                                                </span>
                                                            )}
                                                        </div>
                                                    </div>

                                                    {/* Delete Button */}
                                                    <button
                                                        onClick={() => handleDeleteTask(task.id)}
                                                        className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors opacity-0 group-hover:opacity-100"
                                                        title="Excluir"
                                                    >
                                                        <span className="material-symbols-outlined text-lg">delete</span>
                                                    </button>
                                                </div>
                                            );
                                        })}
                                    </div>
                                )}
                            </div>
                        );
                    })
                )}
            </div>

            {/* Add Task Section */}
            <div className="px-6 py-4 border-t border-gray-100 bg-yellow-50/30">
                {isAddingTask ? (
                    <div className="flex gap-2">
                        <input
                            type="text"
                            value={newTaskTitle}
                            onChange={(e) => setNewTaskTitle(e.target.value)}
                            placeholder="Nome da tarefa..."
                            className="flex-1 px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500 outline-none"
                            onKeyDown={(e) => e.key === 'Enter' && handleAddTask()}
                            autoFocus
                        />
                        <button
                            onClick={handleAddTask}
                            className="px-4 py-2 bg-amber-500 text-white text-xs font-bold rounded-lg hover:bg-amber-600 transition-colors"
                        >
                            Adicionar
                        </button>
                        <button
                            onClick={() => setIsAddingTask(false)}
                            className="px-3 py-2 text-gray-500 text-xs font-bold hover:bg-gray-100 rounded-lg transition-colors"
                        >
                            Cancelar
                        </button>
                    </div>
                ) : (
                    <button
                        onClick={() => setIsAddingTask(true)}
                        className="w-full py-3 border-2 border-dashed border-amber-200 rounded-xl text-sm font-bold text-amber-600 hover:bg-amber-50 hover:border-amber-300 transition-all flex items-center justify-center gap-2"
                    >
                        <span className="material-symbols-outlined text-lg">add</span>
                        Adicionar Tarefa Manual
                    </button>
                )}
            </div>
        </div>
    );
};

export default TaskChecklist;
